env:
  es6: true
  browser: true
  commonjs: true

extends: ['htmlacademy/es6', 'plugin:react/recommended', 'prettier']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 10
  sourceType: module

parser: 'babel-eslint'

plugins: ['react']

settings:
  react:
    version: '16'

rules:
  object-curly-spacing: [2, 'always']
  camelcase: [0]
  no-console: [0]
